### ISSUE TITLE
Statement in Garbage-collected section is wrong

### ISSUE THREAD

**Issue by FROGbots-4634** [LearnWhileDoing/robotics-java#1]
The Garbage-collected section begins thusly:

```
In programming, there is a concept known as memory. The more memory your program uses, the slower it will run, and the less efficient it will be.
```

This statement is simply not true. In many cases preloading things into memory will allow it to run much faster and more efficiently than continually having to go somewhere else to fetch that data. Now, of course, if the program uses so much memory that the operating system has to start paging to virtual memory on disk, then, yes, the program will slow down dramatically.

**Comment by chroline** [comment]
Thanks for the suggestion! While it is true that in some cases using optimization techniques like memoization can make programs run faster, this course isn't meant to cover the intricacies of Java programming (including dealing with memory-intensive programs). For the sake of being concise and for the course to be understandable at all levels, we'd prefer to keep it as "general" as possible.
