### ISSUE TITLE
What is an OpMode page implies that LinearOpMode is only for auto and OpMode is only for tele

### ISSUE THREAD

**Issue by FROGbots-4634** [LearnWhileDoing/robotics-java#3]
This is not accurate. Both LinearOpMode and OpMode can be used for either autonomous or teleop programs. If a team wants to write their autonomous program as a state machine, then they could use an iterative OpMode. Also, if a team simply puts a `while(opModeIsActive())` loop in a LinearOpMode, it can be used for teleop.

**Comment by chroline** [comment]
The course content is truly only supposed to give a general overview on how to get started with programming for FTC and to learn about Java along the way. If a student/team wants to go above and beyond with what they take from this course and do more experimentation to see what works for them, that's great, but for now that isn't the objective of this material. Your thoughts are very appreciated however!
