### ISSUE TITLE
Your first opmode page does not provide a good code example

### ISSUE THREAD

**Issue by FROGbots-4634** [LearnWhileDoing/robotics-java#4]
The page lists the following code:

```java
package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

@Autonomous
public class MyFIRSTJavaOpMode extends LinearOpMode {
    @Override
    public void runOpMode() throws InterruptedException {
    
    }
}
```

And the directions speak thusly:

> When you are ready, tap the INIT button. (If you have code in the runOpMode() method, the code before waitForStart() will execute.) Then, tap the start button. (If you have code in the runOpMode() method, the code after waitForStart() will execute.) The OpMode should stop by itself.

However, as the code does not have a waitForStart() call, if you press init, the OpMode will run through instantly and dump you back at the init button, without ever having shown the start button.

**Comment by chroline** [comment]
Good catch, we will update the lesson to reflect this information. Thanks!
